---
- name: Setup Vagrant environment
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    - vagrantpath: ../../vagrant/$vagrantdir
  tasks: 
    - name: Creating directory
      file: path=$vagrantpath
            state=directory
    - name: Create Vagrantfile
      template: src=templates/Vagrantfile.j2
                dest=$vagrantpath/Vagrantfile
    - name: Copy inventory.ini
      template: src=templates/inventory.j2
                dest=$vagrantpath/inventory.ini
    - name: Copy playbook
      copy: src=files/playbook.yml
            dest=$vagrantpath/playbook.yml
